function B=Bhat(c,kx,ky,z,epsilon,x0,y0)

B=exp(-sqrt(-1).*(kx.*x0+ky.*y0)).*((1/8).*c.^(-2).*exp(1).^((-1/4).*c.^2.*epsilon.^2+(-1).*epsilon.^(-2).* ...
  z.^2).*epsilon.*pi.^(-3/2)+(1/16).*c.^(-3).*exp(1).^((-1).*c.*z).*pi.^( ...
  -1).*(1+c.*z).*erfc((1/2).*c.*epsilon+(-1).*epsilon.^(-1).*z)+(1/16).* ...
  c.^(-3).*exp(1).^(c.*z).*pi.^(-1).*(1+(-1).*c.*z).*erfc((1/2).*c.* ...
  epsilon+epsilon.^(-1).*z));
