function B=BHatGaussMoments(c,kx,ky,z,epsilon,x0,y0)

B= exp(-sqrt(-1).*(kx.*x0+ky.*y0)) .* ( (1/96).*c.^(-3).*pi.^(-1).*(c.*exp(1).^((-1/4).*c.^2.*epsilon.^2+(-1).* ...
  epsilon.^(-2).*z.^2).*epsilon.*pi.^(-1/2).*(12+c.^4.*epsilon.^4+c.^2.*( ...
  2.*epsilon.^2+(-4).*z.^2))+6*exp(1).^((-1).*c.*z).*(1+c.*z).*erfc((1/2).* ...
  c.*epsilon+(-1).*epsilon.^(-1).*z)+6*exp(1).^(c.*z).*(1+(-1).*c.*z).*erfc( ...
  (1/2).*c.*epsilon+epsilon.^(-1).*z)) );
