function Bprime = dBhatDzGaussMoments(c,kx,ky,z,epsilon,x0,y0)

Bprime = exp(-sqrt(-1).*(kx.*x0+ky.*y0)) .* ( (-1/48).*exp(1).^((-1/4).* ...
    c.^2.*epsilon.^2+(-1).*epsilon.^(-2).* z.^2).*pi.^(-3/2).* ...
    (6.*epsilon.*z+c.^2.*epsilon.^3.*z+(-4).*epsilon.^(-1).*z.^3)+ ... 
    (-1/16).*c.^(-1).*pi.^(-1).*z.*(exp(1).^((-1) *c.*z).*erfc((1/2).* ...
    c.*epsilon+(-1).*epsilon.^(-1).*z)+exp(1).^( c.*z).*erfc((1/2).* ...
    c.*epsilon+epsilon.^(-1).*z)) );